/**
 * The signature mark, stored as a 128x128 1-bit bitmap.
 *
 * Keeping it here rather than loading /profile_*.png means the hero canvas
 * needs no network request, no image decode and no raster upscaling - the
 * points are scaled as coordinates, so the mark stays sharp at any size.
 */
const MARK = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAHgAAAAAAAAAAAAAAAAAAAB4AAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAfAAAAAAAAAAAAAAAAAAAAHgAAAAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAeAAAAAAAAAAAAAAAAAAAAHgAAAAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAfAAAAAAAAAAAAAAAAAAAAHgAAAAAAAAAAAAAAAAAAAD4AAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAfAAAAAAAAAAAAAAAAAAAAPgAAAAAAAAAAAAAAAAOAAD4AAAAAAAAAAAAAAAAPwAB8AAAAAAAAAAAAAAAAH+AAfAAAAAAAAAAAAAAAAD/gAPgAAAAAAAAAAAAAAAD9wAD4AAAAAAAAAAAAAAAB88AB+AAAAAAAAAAAAAAAA+PAA/AAAAAAAAAAAAAAAAfHgAPwAAAAAAAAAAAAAAAPh4AH4AAAAAAAAAAAAAAAHw8AB+AAAAA+AAAAAAAAAD4PAA/AAAAD/4AAAAAAAAB8DwAPwAAAH/+AAAAAAAAA+B4AH8AAAP//gAAAAAAAAfAeAB+AAAP/B4AAAAAAAAPgPAA/gAAP+A+AAAAAAAAHwDwAf4AAP8APAAAAAAAAD4B4AH8AAP8AHgAAAAAAAA8AeAD/AAH4ADwAAAAAAAAeAPgA/gAH8AB4AAAAAAAAPADwAd4AD8AA8AAAAAAAAHgA8APeAD8AAeAAAAAAAADwAeADvAB+AAPAAAAAAAAB4AHgB7wA+AAHgAAAAAAAAcAD4Ac8A/AADwAAAAAAAAOAA8AOeAfAAB4AAAAAAAAHAAfAHngPgAAYAAAAAAAADwAHgBx4HwAAMAAAAAAAAA4AB4A48D4AAAAAAAAAAAAcAA8AOPA8AAAAAAAAAAAAOAAPAHDweAAAAAAAAAAAADAADwDw8PAAAAAAAAAAAAAgAB4A4eDgAAAAAAAAAAAAAAAeAcHh4AAAAAAAAAAAAAAAPgPB4cAAAAAAAAAAAAAAADwDgeHgAAAAAAD8AAAAAAA8B4HA+AAAAAH//+AAAAAAfA8BwH//gAA////4AAAAAHgOA8A///+H/8AAeAAAAAB4HgPAI/////AAADgAAAAAeDwDwGAAB/+AAAAwAAAAAPA4A8DAAH//wAAAYAAAAADweAPBgAP/A/AAAEAAAAAA8PADwwA/8AD4AACAAAAAAPDgAc8B/4AAfAAAAAAAAADh4AH+D/gAADwAAAAAAAAA48AA+H/AAAAeAAAAAAAAAOeAAHP+AAAAHgAAAAAAAAD/AAA/8AAQAB4AAAAAAAAA/gAB/4AA4AAeAAAAAAAAAHwAB/wAA4AAHgAAAAAAAAA4AD/gAA4AADwAAAAAAAAAAAH/AAA4AAB8AAAAAAAAAAAP+AAAcAAAeAAAAAAAAAAAP8AAAcAAAPgAAAAAAAAAAf4AAAeAAAHwAAAAAAAAAAfwAAAOAAAD4AAAAAAAAAA/wAAAPAAAB8AAAAAAAAAA/gAAAHgAAA+AAAAAAAAAB/AAAADgAAA/AAAAAAAAAB/AAAADwAAAfgAAAAAAAAB+AAAAB4AAAfwAAAAAAAAB8AAAAA8AAAPwAAAAAAAAB8AAAAAeAAAP4AAAAAAAAB4AAAAAPAAAP8AAAAAAAAB4AAAAAHgAAH8AAAAAAAABwAAAAABwAAP8AAAAAAAABwAAAAAA4AAP+AAAAAAAAAwAAAAAAeAAP+AAAAAAAAAAAAAAAAHAAf+AAAAAAAAAAAAAAAABwA/8AAAAAAAAAAAAAAAAAeD/8AAAAAAAAAAAAAAAAAH//4AAAAAAAAAAAAAAAAAA//wAAAAAAAAAAAAAAAAAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='

const GRID = 128

let cache: SignatureMark | null = null

export interface SignatureMark {
  /** Points normalised into a centred unit square. */
  points: Array<[number, number]>
  /** Width of the mark in grid cells, used to derive dot spacing. */
  span: number
}

export function signatureMark(): SignatureMark {
  if (cache) {
    return cache
  }

  const raw = atob(MARK)
  const cells: Array<[number, number]> = []

  let minX = GRID
  let minY = GRID
  let maxX = 0
  let maxY = 0

  for (let y = 0; y < GRID; y++) {
    for (let x = 0; x < GRID; x++) {
      const i = y * GRID + x

      if (!(raw.charCodeAt(i >> 3) & (1 << (7 - (i & 7))))) {
        continue
      }

      cells.push([x, y])
      minX = Math.min(minX, x)
      minY = Math.min(minY, y)
      maxX = Math.max(maxX, x)
      maxY = Math.max(maxY, y)
    }
  }

  const width = maxX - minX
  const height = maxY - minY
  const span = Math.max(width, height)

  cache = {
    span,
    points: cells.map(([x, y]) => [
      (x - minX - width / 2) / span + 0.5,
      (y - minY - height / 2) / span + 0.5,
    ]),
  }

  return cache
}
